import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from 'next-auth';
import SessionProvider from "./components/SessionProvider";
import Home from "./page";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ 
  children, 
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <NavBar />
            {children}
        </SessionProvider>
      </body>
    </html>
  );
}
