import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from 'next-auth';
import Providers from "./Providers";
import Home from "./page";
import NavigationBar from "./NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pawductivity Pup",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavigationBar />

          {children}
        </Providers>
      </body>
    </html>
  );
}
